server:
  port: 8082

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/microservices

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: menu-service
          uri: lb://MENU-SERVICE
          predicates:
            - Path=/menus/**

        - id: feedback-service
          uri: lb://FEEDBACK-SERVICE
          predicates:
            - Path=/feedbacks/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/deliveries/**

        - id: blog-service
          uri: http://blog-service:3001
          predicates:
            - Path=/blogs/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/