spring.application.name=Gateway
server.port=8083


eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG



spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/Job_Board_Realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/Job_Board_Realm/protocol/openid-connect/certs