spring.application.name=order-service
server.port=8086

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

spring.config.import=optional:configserver:http://config-server:8888

spring.datasource.url=jdbc:h2:file:/data/orderdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always